# Generated by Django 5.2.4 on 2025-07-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='showtime',
            name='total_seats',
            field=models.IntegerField(default=100),
        ),
    ]
