# Generated by Django 5.2.4 on 2025-07-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_is_paid_booking_phone_number_booking_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
    ]
