# Generated by Django 5.2.4 on 2025-07-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=20),
        ),
    ]
