# Generated by Django 5.2.4 on 2025-07-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_trailer',
            field=models.URLField(blank=True, help_text='YouTube or video trailer link', null=True),
        ),
    ]
